# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: strategy_manager.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'strategy_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16strategy_manager.proto\x12\x08strategy\"\x9f\x01\n\rSignalMessage\x12\x15\n\rstrategy_name\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimeframe\x18\x03 \x01(\t\x12\x13\n\x0bsignal_type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x13\n\x0b\x65ntry_price\x18\x06 \x01(\x01\x12\n\n\x02sl\x18\x07 \x01(\x01\x12\n\n\x02tp\x18\x08 \x01(\x01\"T\n\x0e\x45xecutionOrder\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x01\x12\n\n\x02sl\x18\x04 \x01(\x01\x12\n\n\x02tp\x18\x05 \x01(\x01\"N\n\x11\x45xecutionResponse\x12(\n\x06orders\x18\x01 \x03(\x0b\x32\x18.strategy.ExecutionOrder\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\x0fStrategyManager\x12\x42\n\nSendSignal\x12\x17.strategy.SignalMessage\x1a\x1b.strategy.ExecutionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALMESSAGE']._serialized_start=37
  _globals['_SIGNALMESSAGE']._serialized_end=196
  _globals['_EXECUTIONORDER']._serialized_start=198
  _globals['_EXECUTIONORDER']._serialized_end=282
  _globals['_EXECUTIONRESPONSE']._serialized_start=284
  _globals['_EXECUTIONRESPONSE']._serialized_end=362
  _globals['_STRATEGYMANAGER']._serialized_start=364
  _globals['_STRATEGYMANAGER']._serialized_end=449
# @@protoc_insertion_point(module_scope)
