api_key: "6738916d3f9d354223cadde2ec28aabb"
secret_key: "d5c70f1eef15abc72569a6ce9f07f933"
uri_prefix: "https://fapi.bitunix.com"
private_ws_uri: "wss://fapi.bitunix.com/private/"
reconnect_interval: 5
