# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/strategy.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/strategy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/strategy.proto\x12\x05proto\"\xbd\x01\n\rSignalMessage\x12\x15\n\rstrategy_name\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimeframe\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x13\n\x0b\x65ntry_price\x18\x06 \x01(\x01\x12\x11\n\tstop_loss\x18\x07 \x01(\x01\x12\x13\n\x0btake_profit\x18\x08 \x01(\x01\x12\x11\n\ttimestamp\x18\t \x01(\x03\"T\n\x11\x45xecutionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0f\n\x07\x63\x61pital\x18\x03 \x01(\x01\x12\x0f\n\x07message\x18\x04 \x01(\t2O\n\x0fStrategyManager\x12<\n\nSendSignal\x12\x14.proto.SignalMessage\x1a\x18.proto.ExecutionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.strategy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALMESSAGE']._serialized_start=32
  _globals['_SIGNALMESSAGE']._serialized_end=221
  _globals['_EXECUTIONRESPONSE']._serialized_start=223
  _globals['_EXECUTIONRESPONSE']._serialized_end=307
  _globals['_STRATEGYMANAGER']._serialized_start=309
  _globals['_STRATEGYMANAGER']._serialized_end=388
# @@protoc_insertion_point(module_scope)
